### ISSUE TITLE
Title Color UI/UX

### ISSUE THREAD

**Issue by jyot404** [JyotDhamelia/Git-Hub-Adite#1]
I think the heading will look better if the color is set to be more orange.

```css
h1 {
  color: #e69f23;
}
```
